file {'resolv.conf':  # Creation of /etc/resolv.conf file
path => '/etc/resolv.conf',
content =>
'# Generated by Puppet
search darole.org 
nameserver 172.16.1.200 
nameserver 192.168.2.1 
options timeout:2
',
}
